name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential

      - name: Install Norminette
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
          python3 -m pip install pipx
          pipx install norminette

      - name: Run Norminette
        run: |
          norminette src/command include/

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          make test
